# Generated by Django 3.2.10 on 2022-01-26 05:58

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('cart', '0003_auto_20220124_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartlist',
            options={},
        ),
        migrations.AlterModelTable(
            name='cartlist',
            table=None,
        ),
        migrations.AlterModelTable(
            name='wardrobe',
            table=None,
        ),
    ]
